// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { v4 as uuidv4 } from 'uuid';

const SUPABASE_URL = "https://pvsjjqmsoauuxxfgdhfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2c2pqcW1zb2F1dXh4ZmdkaGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTI5NTUsImV4cCI6MjA1ODY4ODk1NX0.Mp6zyYRkHfHZTkBIkV_lpYv8nkAkJ9i7cI1y8dGGF6M";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true
  }
});

// Função para verificar a conexão com o Supabase
export async function checkSupabaseConnection() {
  try {
    const { data, error } = await supabase.from('vehicles').select('id').limit(1);
    
    if (error) throw error;
    
    return { success: true, data };
  } catch (error) {
    return { success: false, error };
  }
}

// Função para buscar veículos do Supabase
export async function getVehiclesFromSupabase() {
  try {
    console.log("Buscando veículos do Supabase...");
    
    const { data, error } = await supabase
      .from('vehicles')
      .select('*')
      .order('brand', { ascending: true });
      
    if (error) {
      console.error("Erro ao buscar veículos:", error);
      return { success: false, error, vehicles: [] };
    }
    
    console.log(`Recuperados ${data?.length || 0} veículos com sucesso`);
    return { success: true, vehicles: data || [] };
  } catch (error) {
    console.error("Erro inesperado ao buscar veículos:", error);
    return { success: false, error, vehicles: [] };
  }
}

// Função para converter IDs de timestamp para formato UUID
const convertToValidUuid = (id: string | number): string => {
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  if (typeof id === 'string' && uuidRegex.test(id)) {
    return id;
  }
  return uuidv4();
};

// Função para salvar cliente no Supabase
export async function saveClientToSupabase(client: any) {
  try {
    const clientId = convertToValidUuid(client.id);

    const { data, error } = await supabase
      .from('clients')
      .upsert({
        id: clientId,
        name: client.name,
        document: client.document || null,
        email: client.email || null,
        updated_at: new Date().toISOString()
      })
      .select()
      .single();

    if (error) {
      return { success: false, error };
    }

    return { success: true, data };
  } catch (error) {
    return { success: false, error };
  }
}

// Função para salvar orçamento no Supabase
export async function saveQuoteToSupabase(quote: any) {
  try {
    console.log("Iniciando salvamento de orçamento no Supabase:", quote);
    
    let userId = null;
    const adminUserStr = localStorage.getItem('admin_user');
    if (adminUserStr) {
      const adminUser = JSON.parse(adminUserStr);
      userId = adminUser.id;
    } else {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.user) {
        userId = session.user.id;
      }
    }
    
    // Salvar cliente
    const clientResult = await saveClientToSupabase(quote.client);
    if (!clientResult.success) {
      console.error("Erro ao salvar cliente:", clientResult.error);
      return { success: false, error: clientResult.error };
    }

    const isValidUuid = !!quote.id && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(quote.id);
    const quoteId = isValidUuid ? quote.id : uuidv4();
    const clientUuid = clientResult.data.id;
    
    // Dados principais do orçamento
    const quoteData: any = {
      id: quoteId,
      client_id: clientUuid,
      contract_months: quote.contractMonths || quote.globalParams?.contractMonths || 12,
      monthly_km: quote.monthlyKm || quote.globalParams?.monthlyKm || 2000,
      operation_severity: quote.operationSeverity || quote.globalParams?.operationSeverity || 3,
      has_tracking: quote.hasTracking || quote.globalParams?.hasTracking || false,
      total_value: quote.totalCost || 0,
      status: 'active',
      title: quote.title || `Orçamento ${new Date().toLocaleDateString('pt-BR')}`,
      created_by: userId
    };
    
    console.log("Salvando orçamento com dados:", quoteData);
    
    const { data, error } = await supabase
      .from('quotes')
      .upsert(quoteData)
      .select();

    if (error) {
      console.error("Erro ao salvar orçamento:", error);
      return { success: false, error };
    }
    
    console.log("Orçamento salvo com sucesso. ID:", quoteId);
    
    // Salvar veículos associados ao orçamento
    if (quote.vehicles && quote.vehicles.length > 0) {
      console.log(`Processando ${quote.vehicles.length} veículos para salvar...`);
      
      // Primeiro, removemos quaisquer associações existentes se estiver atualizando um orçamento
      if (isValidUuid) {
        console.log("Removendo associações de veículos existentes para orçamento:", quoteId);
        const { error: deleteError } = await supabase
          .from('quote_vehicles')
          .delete()
          .eq('quote_id', quoteId);
          
        if (deleteError) {
          console.error("Erro ao remover associações de veículos existentes:", deleteError);
        }
      }
      
      // Extrair resultados de cálculo se disponíveis
      let quoteResults = null;
      if (quote.vehicleResults && Array.isArray(quote.vehicleResults)) {
        console.log("Usando resultados de cálculo pré-existentes:", quote.vehicleResults);
        quoteResults = quote.vehicleResults;
      } else if (quote.result && quote.result.vehicleResults) {
        console.log("Usando resultados de cálculo do objeto result:", quote.result.vehicleResults);
        quoteResults = quote.result.vehicleResults;
      }
      
      // Promessas para inserções de veículos
      const vehicleInsertPromises = [];
      
      // Processar cada veículo
      for (let i = 0; i < quote.vehicles.length; i++) {
        const vehicleItem = quote.vehicles[i];
        console.log("Processando item do veículo:", vehicleItem);
        
        // CORREÇÃO: Lidar com diferentes estruturas de veículos
        let vehicle;
        
        // Se vehicleItem tem a propriedade 'vehicle', use-a diretamente
        if (vehicleItem.vehicle) {
          vehicle = vehicleItem.vehicle;
          console.log("Usando vehicle do objeto vehicleItem:", vehicle);
        } 
        // Se vehicleItem tem a propriedade 'vehicleId', pode ser um veículo do formato da tabela
        else if (vehicleItem.vehicleId) {
          // Criar um objeto de veículo a partir dos dados disponíveis no vehicleItem
          vehicle = {
            id: vehicleItem.vehicleId,
            brand: vehicleItem.vehicleBrand || "",
            model: vehicleItem.vehicleModel || "",
            year: vehicleItem.year || new Date().getFullYear(),
            value: vehicleItem.value || 0,
            plateNumber: vehicleItem.plateNumber || null,
            isUsed: vehicleItem.isUsed || false,
            groupId: vehicleItem.groupId || "A",
            color: vehicleItem.color || null,
            odometer: vehicleItem.odometer || 0,
            tipoCombustivel: vehicleItem.tipoCombustivel || null
          };
          console.log("Construindo objeto vehicle a partir dos campos:", vehicle);
        }
        // Se não há estrutura específica, usar o próprio item como veículo
        else {
          vehicle = vehicleItem;
          console.log("Usando o próprio vehicleItem como veículo:", vehicle);
        }
        
        // CORREÇÃO: Se vehicleItem não tem estrutura reconhecida
        if (!vehicle) {
          console.error("Veículo com estrutura não reconhecida:", vehicleItem);
          continue;
        }
        
        console.log("Dados do veículo para processamento:", vehicle);

        // Verificar se o veículo já existe no Supabase
        let vehicleId = null;
        
        // Primeiro, tenta pelo ID do veículo
        if (vehicle.id) {
          const { data: existingVehicleById } = await supabase
            .from('vehicles')
            .select('id')
            .eq('id', vehicle.id)
            .limit(1);
            
          if (existingVehicleById && Array.isArray(existingVehicleById) && existingVehicleById.length > 0) {
            vehicleId = existingVehicleById[0].id;
            console.log("Veículo existente encontrado pelo ID:", vehicleId);
            
            // CORREÇÃO: Atualizar os dados do veículo existente com as informações corretas
            const updateData = {
              brand: vehicle.brand || 'Não especificado',
              model: vehicle.model || 'Não especificado',
              year: parseInt(vehicle.year) || new Date().getFullYear(),
              value: parseFloat(vehicle.value) || 0,
              plate_number: vehicle.plateNumber || vehicle.plate_number || null,
              is_used: vehicle.isUsed === true || vehicle.is_used === true || (vehicle.plateNumber || vehicle.plate_number ? true : false), // Corrigido para determinar is_used com base na presença de placa
              group_id: vehicle.groupId || vehicle.group_id || 'A',
              color: vehicle.color || null,
              odometer: parseInt(vehicle.odometer) || 0,
              fuel_type: vehicle.fuelType || vehicle.fuel_type || vehicle.tipoCombustivel || null
            };
            
            console.log("Atualizando veículo existente com dados:", updateData);
            
            const { error: updateError } = await supabase
              .from('vehicles')
              .update(updateData)
              .eq('id', vehicleId);
              
            if (updateError) {
              console.error("Erro ao atualizar dados do veículo:", updateError);
            } else {
              console.log("Dados do veículo atualizados com sucesso");
            }
          }
        }
        
        // Se não encontrou pelo ID, tenta pela placa (se disponível)
        if (!vehicleId && (vehicle.plateNumber || vehicle.plate_number)) {
          const plateToSearch = vehicle.plateNumber || vehicle.plate_number;
          console.log(`Buscando veículo pela placa: ${plateToSearch}`);
          
          const { data: existingVehicles } = await supabase
            .from('vehicles')
            .select('id')
            .eq('plate_number', plateToSearch)
            .limit(1);
            
          if (existingVehicles && Array.isArray(existingVehicles) && existingVehicles.length > 0) {
            vehicleId = existingVehicles[0].id;
            console.log("Veículo existente encontrado pela placa:", vehicleId);
            
            // CORREÇÃO: Atualizar os dados do veículo existente com as informações corretas
            const updateData = {
              brand: vehicle.brand || 'Não especificado',
              model: vehicle.model || 'Não especificado',
              year: parseInt(vehicle.year) || new Date().getFullYear(),
              value: parseFloat(vehicle.value) || 0,
              is_used: true, // Veículos com placa são sempre usados
              group_id: vehicle.groupId || vehicle.group_id || 'A',
              color: vehicle.color || null,
              odometer: parseInt(vehicle.odometer) || 0,
              fuel_type: vehicle.fuelType || vehicle.fuel_type || vehicle.tipoCombustivel || null
            };
            
            console.log("Atualizando veículo existente com dados:", updateData);
            
            const { error: updateError } = await supabase
              .from('vehicles')
              .update(updateData)
              .eq('id', vehicleId);
              
            if (updateError) {
              console.error("Erro ao atualizar dados do veículo:", updateError);
            } else {
              console.log("Dados do veículo atualizados com sucesso");
            }
          }
        }
        
        // Se ainda não encontrou o veículo, cria um novo
        if (!vehicleId) {
          console.log("Criando novo veículo com dados:", vehicle);
          
          // CORREÇÃO PRINCIPAL: Garantir que todos os tipos de veículos (novos ou usados) sejam salvos
          // Corrigimos aqui para criar veículos novos (sem placa) também
          const vehicleData = {
            brand: vehicle.brand || 'Não especificado',
            model: vehicle.model || 'Não especificado',
            year: parseInt(vehicle.year) || new Date().getFullYear(),
            value: parseFloat(vehicle.value) || 0,
            plate_number: vehicle.plateNumber || vehicle.plate_number || null,
            // CORREÇÃO: Agora determinamos is_used explicitamente
            // Veículos com placa são sempre usados, ou se a propriedade isUsed estiver definida como true
            is_used: vehicle.plateNumber || vehicle.plate_number ? true : (vehicle.isUsed === true || vehicle.is_used === true), 
            group_id: vehicle.groupId || vehicle.group_id || 'A',
            color: vehicle.color || null,
            odometer: parseInt(vehicle.odometer) || 0,
            fuel_type: vehicle.fuelType || vehicle.fuel_type || vehicle.tipoCombustivel || null
          };
          
          console.log("Dados formatados do veículo para inserção:", vehicleData);
          
          const { data: newVehicle, error: vehicleError } = await supabase
            .from('vehicles')
            .insert(vehicleData)
            .select()
            .single();
            
          if (vehicleError) {
            console.error("Erro ao criar veículo:", vehicleError);
            continue;
          }
          
          vehicleId = newVehicle.id;
          console.log("Novo veículo criado com ID:", vehicleId);
        }
        
        // Obter parâmetros do veículo
        let params = quote.useGlobalParams 
          ? quote.globalParams 
          : (vehicleItem.params || quote.globalParams);
        
        if (!params) {
          console.log("Parâmetros não encontrados, usando padrões");
          params = {
            contractMonths: quote.contractMonths || 12,
            monthlyKm: quote.monthlyKm || 2000,
            operationSeverity: quote.operationSeverity || 3,
            hasTracking: quote.hasTracking || false
          };
        }
        
        // Determinar valores de custos
        let monthlyValue = 0;
        let depreciationCost = 0;
        let maintenanceCost = 0;
        let extraKmRate = 0;
        let totalCost = 0;
        
        // Verificar se há resultados calculados disponíveis
        if (quoteResults && Array.isArray(quoteResults)) {
          const vehicleResult = quoteResults.find(r => r.vehicleId === vehicle.id);
          if (vehicleResult) {
            depreciationCost = vehicleResult.depreciationCost || 0;
            maintenanceCost = vehicleResult.maintenanceCost || 0;
            extraKmRate = vehicleResult.extraKmRate || 0;
            totalCost = vehicleResult.totalCost || vehicleResult.monthlyValue || 0;
            monthlyValue = totalCost;
            console.log("Valores calculados encontrados:", {depreciationCost, maintenanceCost, totalCost});
          }
        }
        
        // Se não temos valores calculados, verificar outros campos
        if (totalCost === 0) {
          if (vehicleItem.monthlyValue !== undefined) {
            monthlyValue = vehicleItem.monthlyValue;
            totalCost = monthlyValue;
          } else if (vehicleItem.total_cost !== undefined) {
            totalCost = vehicleItem.total_cost;
            monthlyValue = totalCost;
          } else if (quote.totalCost && quote.vehicles.length > 0) {
            // Dividir o valor total pelo número de veículos como último recurso
            totalCost = quote.totalCost / quote.vehicles.length;
            monthlyValue = totalCost;
          }
          
          console.log("Valor mensal atribuído:", monthlyValue);
        }
        
        // Preparar os dados para inserção
        const quoteVehicleData = {
          quote_id: quoteId,
          vehicle_id: vehicleId,
          monthly_value: monthlyValue,
          monthly_km: params.monthlyKm,
          contract_months: params.contractMonths,
          operation_severity: params.operationSeverity,
          has_tracking: params.hasTracking,
          depreciation_cost: depreciationCost,
          maintenance_cost: maintenanceCost,
          extra_km_rate: extraKmRate,
          total_cost: totalCost
        };
        
        console.log("Inserindo veículo na tabela quote_vehicles:", quoteVehicleData);
        
        // Adicionar a promessa ao array
        const insertPromise = supabase
          .from('quote_vehicles')
          .insert(quoteVehicleData)
          .select();
          
        vehicleInsertPromises.push(insertPromise);
      }
      
      // Aguardar todas as inserções de veículos
      if (vehicleInsertPromises.length > 0) {
        console.log(`Aguardando conclusão de ${vehicleInsertPromises.length} inserções de veículos...`);
        const results = await Promise.allSettled(vehicleInsertPromises);
        
        // Log de resultados
        const successCount = results.filter(r => r.status === 'fulfilled').length;
        const failureCount = results.filter(r => r.status === 'rejected').length;
        
        console.log(`Inserções concluídas: ${successCount} sucesso, ${failureCount} falhas`);
        
        // Log de erros de inserção para diagnóstico
        results.forEach((result, index) => {
          if (result.status === 'rejected') {
            console.error(`Erro na inserção do veículo ${index}:`, result.reason);
          }
        });
      } else {
        console.log("Nenhum veículo para inserir");
      }
    } else {
      console.log("Nenhum veículo para associar ao orçamento");
    }
    
    return { success: true, data: [{ id: quoteId }] };
  } catch (error) {
    console.error("Erro inesperado ao salvar orçamento:", error);
    return { success: false, error };
  }
}

// Função para buscar orçamentos no Supabase
export async function getQuotesFromSupabase() {
  try {
    console.log("Buscando orçamentos do Supabase...");
    
    const { data, error } = await supabase
      .from('quotes')
      .select(`
        *,
        client:client_id(*)
      `)
      .order('created_at', { ascending: false });
      
    if (error) {
      throw error;
    }
    
    // Buscar veículos para cada orçamento
    const quotes = Array.isArray(data) ? data : [];
    for (const quote of quotes) {
      const { data: vehiclesData } = await supabase
        .from('quote_vehicles')
        .select(`
          *,
          vehicle:vehicle_id(*)
        `)
        .eq('quote_id', quote.id);
        
      // Adicionar veículos ao objeto de orçamento como propriedade não-tipada
      (quote as any).vehicles = vehiclesData || [];
    }
    
    console.log("Orçamentos recuperados:", quotes.length);
    return { success: true, quotes };
  } catch (error) {
    console.error("Erro inesperado ao buscar orçamentos:", error);
    return { success: false, error, quotes: [] };
  }
}

// Função para buscar um único orçamento pelo ID
export async function getQuoteByIdFromSupabase(quoteId: string) {
  try {
    console.log(`Buscando orçamento com ID: ${quoteId}`);
    
    const { data, error } = await supabase
      .from('quotes')
      .select(`
        *,
        client:client_id(*)
      `)
      .eq('id', quoteId)
      .single();
      
    if (error) {
      console.error("Erro ao buscar orçamento por ID:", error);
      return { success: false, error };
    }
    
    // Buscar veículos associados a este orçamento
    if (data) {
      const { vehicles, success } = await getQuoteVehicles(quoteId);
      
      if (success && vehicles && Array.isArray(vehicles)) {
        (data as any).vehicles = vehicles;
        console.log(`Veículos associados ao orçamento ${quoteId}:`, vehicles);
      } else {
        (data as any).vehicles = [];
      }
      
      console.log("Orçamento recuperado:", data);
    }
    
    return { success: true, quote: data };
  } catch (error) {
    console.error("Erro inesperado ao buscar orçamento por ID:", error);
    return { success: false, error };
  }
}

export const addVehicleToQuote = async (quoteId: string, vehicleData: any): Promise<{ success: boolean; data?: any; error?: any }> => {
  try {
    // Verificar se o veículo já existe
    let vehicleId = vehicleData.vehicle_id;
    
    if (!vehicleId && vehicleData.vehicle) {
      // Se não tiver ID mas tiver objeto de veículo, verificar se já existe ou criar
      const vehicle = vehicleData.vehicle;
      
      if (vehicle.plateNumber) {
        const { data: existingVehicles } = await supabase
          .from('vehicles')
          .select('id')
          .eq('plate_number', vehicle.plateNumber)
          .limit(1);
          
        if (existingVehicles && Array.isArray(existingVehicles) && existingVehicles.length > 0) {
          vehicleId = existingVehicles[0].id;
        }
      }
      
      // Se ainda não tiver ID, criar veículo
      if (!vehicleId) {
        const { data: newVehicle, error: vehicleError } = await supabase
          .from('vehicles')
          .insert({
            brand: vehicle.brand || 'Não especificado',
            model: vehicle.model || 'Não especificado',
            year: vehicle.year || new Date().getFullYear(),
            value: vehicle.value || 0,
            plate_number: vehicle.plateNumber || null,
            is_used: vehicle.isUsed || false,
            group_id: vehicle.groupId || null
          })
          .select()
          .single();
          
        if (vehicleError) {
          console.error('Erro ao criar veículo:', vehicleError);
          return { success: false, error: vehicleError };
        }
        
        vehicleId = newVehicle.id;
      }
    }
    
    if (!vehicleId) {
      return { success: false, error: { message: 'ID do veículo não fornecido' } };
    }
    
    // Adicionar veículo ao orçamento
    const { data, error } = await supabase
      .from('quote_vehicles')
      .insert({
        quote_id: quoteId,
        vehicle_id: vehicleId,
        monthly_value: vehicleData.monthly_value || 0,
        monthly_km: vehicleData.monthly_km,
        contract_months: vehicleData.contract_months,
        operation_severity: vehicleData.operation_severity,
        has_tracking: vehicleData.has_tracking
      })
      .select();

    if (error) {
      console.error('Erro ao adicionar veículo ao orçamento:', error);
      return { success: false, error };
    }

    return { success: true, data };
  } catch (error) {
    console.error('Erro inesperado ao adicionar veículo ao orçamento:', error);
    return { success: false, error };
  }
};

// Modificar a função getQuoteVehicles para retornar mais detalhes
export const getQuoteVehicles = async (quoteId: string): Promise<{ success: boolean; vehicles?: any[]; error?: any }> => {
  try {
    console.log(`Buscando veículos para o orçamento ${quoteId}...`);
    
    const { data, error } = await supabase
      .from('quote_vehicles')
      .select(`
        id,
        quote_id,
        vehicle_id,
        monthly_value,
        monthly_km,
        contract_months,
        operation_severity,
        has_tracking,
        depreciation_cost,
        maintenance_cost,
        extra_km_rate,
        total_cost,
        vehicle:vehicle_id(*)
      `)
      .eq('quote_id', quoteId);

    if (error) {
      console.error('Erro ao buscar veículos do orçamento:', error);
      return { success: false, error, vehicles: [] };
    }
    
    const vehicles = data || [];
    console.log(`Encontrados ${vehicles.length} veículos para o orçamento ${quoteId}:`, vehicles);
    
    // Processar os veículos para garantir que todos os campos necessários estejam presentes
    const processedVehicles = vehicles.map(vehicle => {
      // Se temos um resultado de cálculo, vamos usá-lo
      const result = {
        depreciationCost: vehicle.depreciation_cost || 0,
        maintenanceCost: vehicle.maintenance_cost || 0,
        extraKmRate: vehicle.extra_km_rate || 0,
        totalCost: vehicle.total_cost || vehicle.monthly_value || 0
      };
      
      return {
        ...vehicle,
        result,
        monthly_value: vehicle.monthly_value || vehicle.total_cost || 0
      };
    });
    
    return { success: true, vehicles: processedVehicles };
  } catch (error) {
    console.error('Erro inesperado ao buscar veículos do orçamento:', error);
    return { success: false, error, vehicles: [] };
  }
};
